[package]
name = "edgefirst-navsat"
description = "EdgeFirst NavSat Service"
repository = "https://github.com/EdgeFirstAI/navsat"
license = "Apache-2.0"
version = "1.5.1"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[features]
default = ["tracy"]
tracy = ["tracing-tracy/enable", "tracy-client/enable"]
profiling = [
    "tracing-tracy/sampling",
    "tracing-tracy/system-tracing",
    "tracy-client/sampling",
    "tracy-client/system-tracing",
]

[dependencies]
clap = { version = "4.5.60", features = ["derive", "env"] }
edgefirst-schemas = "1.5.5"
gpsd_proto = "1.0.0"
itertools = "0.14.0"
libc = "0.2.182"
log = "0.4.28"
serde_json = "1.0.145"
tracing = "0.1.43"
tracing-journald = "0.3.2"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.22"
tracing-tracy = { version = "0.11.4", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
tracy-client = { version = "0.18.4", default-features = false, features = [
    "manual-lifetime",
    "broadcast",
    "ondemand",
    "fibers",
] }
zenoh = "1.7.2"
